### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by BabySharktududu** [statsbomb/statsbombpy#31]
### Contact Details

benkorman12@gmail.com

### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

Python 3.9.7

### What happened?

The events of given player are assumed to be attacking from left to right.

Yet, the Y axis seems to be mirrored.
Events of Spinazzola (LB) are registerd to be on the right of the pitch (near 0).
Can be manually fixed though. Is it my bad or yours?

Thanks for your help

### Attempted solutions

Can do (80 - coordinate) to mirror to normal

**Comment by anenglishgoat** [comment]
This is not really a statsbombpy issue, it's more to do with the data spec. Everything is detailed in the API documentation I linked to before (https://github.com/statsbomb/open-data/blob/master/doc/Open%20Data%20Events%20v4.0.0.pdf). Appendix 2 there outlines the coordinate system we use.

The coordinate system is set up so that the acting team is playing towards x=120, and the left hand side of the pitch is at y=0.

As you say, if you'd prefer to change that coordinate system for plotting purposes, you can just flip the y coordinates.
