### ISSUE TITLE
How can I setup this project to use open-data repo instead API?

### ISSUE THREAD

**Issue by maotoledo** [statsbomb/statsbombpy#53]
### Version

1.0.1

### What platform are you seeing the problem on?

Mac

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

3.8 

### What happened?

I understand that this repo is used for API credentials and Free data from open-data repository. I would like to know how to setup my environment to use it with local data.

**Comment by anenglishgoat** [comment]
If you don't provide credentials, the data will be pulled from the open data repo on github by default.

`public.py` is where that happens, so you could switch out the requests there so that they just read json files you have stored locally instead (if you've already cloned the open data repo, for example).

Does that answer the question?

**Comment by maotoledo** [comment]
It does, ty 👍
